import type { Metadata } from "next";
import "./globals.css";
import ClinetLayout from "./ClientLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ClinetLayout>{children}</ClinetLayout>;
}
